name       : libwnck
version    : 3.30.0
release    : 16
source     :
    - https://download.gnome.org/sources/libwnck/3.30/libwnck-3.30.0.tar.xz : ac6d0d2646aa80676d3066651e73abb7bff7ed79be238c9b21a0083e2adc3439
homepage   : http://www.gnome.org
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Window Navigator Construction Kit
description: |
    The libwnck package contains the Window Navigator Construction Kit.
builddeps  :
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xres)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
