name       : libwnck
version    : '40.1'
release    : 22
source     :
    - https://download.gnome.org/sources/libwnck/40/libwnck-40.1.tar.xz : 03134fa114ef3fbe34075aa83678f58aa2debe9fcef4ea23c0779e28601d6611
homepage   : http://www.gnome.org
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Window Navigator Construction Kit
description: |
    The libwnck package contains the Window Navigator Construction Kit.
builddeps  :
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xres)
    - gtk-doc
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
