name       : libwnck
version    : '43.0'
release    : 24
source     :
    - https://download.gnome.org/sources/libwnck/43/libwnck-43.0.tar.xz : 905bcdb85847d6b8f8861e56b30cd6dc61eae67ecef4cd994a9f925a26a2c1fe
homepage   : http://www.gnome.org
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Window Navigator Construction Kit
description: |
    The libwnck package contains the Window Navigator Construction Kit.
builddeps  :
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xres)
    - gtk-doc
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-segfault-in-invalidate_icons.patch
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
