name       : libwnck
version    : 3.24.1
release    : 14
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libwnck/3.24/libwnck-3.24.1.tar.xz : afa6dc283582ffec15c3374790bcbcb5fb422bd38356d72deeef35bf7f9a1f04
homepage   : http://www.gnome.org
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : Window Navigator Construction Kit
description: |
    The libwnck package contains the Window Navigator Construction Kit.
builddeps  :
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xres)
setup      : |
    %patch -p1 < $pkgfiles/fix-icon-change-event.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
