name       : libwnck
version    : 3.20.1
release    : 9
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libwnck/3.20/libwnck-3.20.1.tar.xz : 1cb03716bc477058dfdf3ebfa4f534de3b13b1aa067fcd064d0b7813291cba72
homepage   : http://www.gnome.org
license    :
    - LGPL-2.1
summary    : Window Navigator Construction Kit
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xres)
description: |
    The libwnck package contains the Window Navigator Construction Kit.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
