name       : libwnck
version    : '40.0'
release    : 21
source     :
    - https://download.gnome.org/sources/libwnck/40/libwnck-40.0.tar.xz : 30cb79a839f90cd66f3e202f3f98cb5166fa0cd9b92eb571ad9c470a43021d83
homepage   : http://www.gnome.org
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Window Navigator Construction Kit
description: |
    The libwnck package contains the Window Navigator Construction Kit.
builddeps  :
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xres)
    - gtk-doc
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
